<template>
    <div class="retouche-properties">
      <h3>Properties</h3>
      
      <div class="properties-grid">
        <!-- Status -->
        <div class="property-item">
          <label class="property-label">
            <span class="label-icon">📊</span>
            Status
          </label>
          <select 
            v-model="localRetouche.status"
            @change="emitChange"
            class="property-select"
          >
            <option value="published">Published</option>
            <option value="invisible">Invisible</option>
          </select>
        </div>
        
        <!-- Description -->
        <div class="property-item full-width">
          <label class="property-label">
            <span class="label-icon">📝</span>
            Description
            <span class="char-count" :class="{ 'warning': descriptionLength > 300 }">
              {{ descriptionLength }}/300
            </span>
          </label>
          <textarea
            v-model="localRetouche.description"
            @input="emitChange"
            placeholder="Describe the retouching work and transformation..."
            class="property-textarea"
            :class="{ 'warning': descriptionLength > 300 }"
            rows="3"
          ></textarea>
          <div class="validation-info" v-if="descriptionLength > 300">
            <span class="validation-warning">⚠️ Description too long for optimal SEO</span>
          </div>
        </div>
      </div>
      
      <!-- SEO Section -->
      <div class="seo-section">
        <h4 class="section-title">
          <span class="section-icon">🔍</span>
          SEO & Metadata
          <button @click="showSeo = !showSeo" class="toggle-section">
            {{ showSeo ? '−' : '+' }}
          </button>
        </h4>
        
        <div v-if="showSeo" class="seo-fields">
          <!-- Auto-generate SEO button -->
          <div class="seo-auto-generate">
            <button 
              @click="autoGenerateSEO"
              class="auto-generate-btn"
              :disabled="!localRetouche.title && !localRetouche.description"
            >
              ✨ Auto-generate SEO
            </button>
            <small>Generate meta title and description from retouche content</small>
          </div>
          
          <!-- SEO Title -->
          <div class="property-item">
            <label class="property-label">
              Meta Title
              <span class="char-count" :class="{ 'warning': seoTitleLength > 60, 'error': seoTitleLength > 80 }">
                {{ seoTitleLength }}/60
              </span>
            </label>
            <input
              v-model="localRetouche.seo.title"
              @input="emitChange"
              type="text"
              :placeholder="autoGeneratedSEO.title || 'Auto-generated from title...'"
              class="property-input"
              :class="{ 'warning': seoTitleLength > 60, 'error': seoTitleLength > 80 }"
            />
            <div class="validation-info" v-if="seoTitleLength > 60">
              <span v-if="seoTitleLength <= 80" class="validation-warning">
                ⚠️ Title may be truncated in search results
              </span>
              <span v-else class="validation-error">
                ❌ Title too long - will be truncated
              </span>
            </div>
          </div>
          
          <!-- SEO Description -->
          <div class="property-item">
            <label class="property-label">
              Meta Description
              <span class="char-count" :class="{ 'warning': seoDescriptionLength > 160, 'error': seoDescriptionLength > 200 }">
                {{ seoDescriptionLength }}/160
              </span>
            </label>
            <textarea
              v-model="localRetouche.seo.description"
              @input="emitChange"
              :placeholder="autoGeneratedSEO.description || 'Auto-generated from description...'"
              class="property-textarea"
              :class="{ 'warning': seoDescriptionLength > 160, 'error': seoDescriptionLength > 200 }"
              rows="2"
            ></textarea>
            <div class="validation-info" v-if="seoDescriptionLength > 160">
              <span v-if="seoDescriptionLength <= 200" class="validation-warning">
                ⚠️ Description may be truncated in search results
              </span>
              <span v-else class="validation-error">
                ❌ Description too long - will be truncated
              </span>
            </div>
          </div>
          
          <!-- SEO Preview -->
          <div class="seo-preview">
            <h5>Search Engine Preview</h5>
            <div class="preview-container">
              <div class="google-preview">
                <div class="preview-url">
                  <span class="domain">portfolio-valentine.com</span>
                  <span class="path">› retouches › {{ generateSlug(localRetouche.title || 'untitled') }}</span>
                </div>
                <div class="preview-title">
                  {{ displaySeoTitle }}
                </div>
                <div class="preview-description">
                  {{ displaySeoDescription }}
                </div>
              </div>
            </div>
          </div>
          
          <!-- Keywords -->
          <div class="property-item">
            <label class="property-label">
              Keywords
              <span class="char-count" :class="{ 'warning': keywordsCount > 8 }">
                {{ keywordsCount }}/10
              </span>
            </label>
            <div class="keywords-input">
              <div class="keywords-list">
                <span
                  v-for="(keyword, index) in keywords"
                  :key="index"
                  class="keyword-tag"
                >
                  {{ keyword }}
                  <button @click="removeKeyword(index)" class="remove-keyword">×</button>
                </span>
              </div>
              <input
                v-model="newKeyword"
                @keydown.enter.prevent="addKeyword"
                @keydown.comma.prevent="addKeyword"
                @keydown.space.prevent="addKeyword"
                type="text"
                placeholder="Add keyword..."
                class="keyword-input"
              />
            </div>
            <div class="keywords-help">
              <small>Press Enter, comma, or space to add keywords</small>
            </div>
          </div>
        </div>
      </div>
      
      <!-- Images Info Section -->
      <div class="images-info-section">
        <h4 class="section-title">
          <span class="section-icon">🖼️</span>
          Images Information
        </h4>
        
        <div class="images-grid">
          <div class="image-info-card">
            <h5>Before Image</h5>
            <div class="image-details">
              <div class="detail-item">
                <span class="detail-label">Dimensions:</span>
                <span class="detail-value">{{ beforeImage?.width || 0 }}×{{ beforeImage?.height || 0 }}px</span>
              </div>
              <div class="detail-item">
                <span class="detail-label">Size:</span>
                <span class="detail-value">{{ formatFileSize(beforeImage?.size || 0) }}</span>
              </div>
              <div class="detail-item">
                <span class="detail-label">Format:</span>
                <span class="detail-value">{{ getFileFormat(beforeImage?.mime_type || '') }}</span>
              </div>
            </div>
          </div>
          
          <div class="image-info-card">
            <h5>After Image</h5>
            <div class="image-details">
              <div class="detail-item">
                <span class="detail-label">Dimensions:</span>
                <span class="detail-value">{{ afterImage?.width || 0 }}×{{ afterImage?.height || 0 }}px</span>
              </div>
              <div class="detail-item">
                <span class="detail-label">Size:</span>
                <span class="detail-value">{{ formatFileSize(afterImage?.size || 0) }}</span>
              </div>
              <div class="detail-item">
                <span class="detail-label">Format:</span>
                <span class="detail-value">{{ getFileFormat(afterImage?.mime_type || '') }}</span>
              </div>
            </div>
          </div>
        </div>
        
        <!-- Compatibility check -->
        <div v-if="beforeImage && afterImage" class="compatibility-check">
          <div class="check-item" :class="{ success: dimensionsMatch, warning: !dimensionsMatch }">
            <span class="check-icon">{{ dimensionsMatch ? '✅' : '⚠️' }}</span>
            <span class="check-text">
              {{ dimensionsMatch ? 'Images have matching dimensions' : 'Images have different dimensions' }}
            </span>
          </div>
          
          <div class="check-item" :class="{ success: aspectRatioMatch, warning: !aspectRatioMatch }">
            <span class="check-icon">{{ aspectRatioMatch ? '✅' : '⚠️' }}</span>
            <span class="check-text">
              {{ aspectRatioMatch ? 'Images have matching aspect ratios' : 'Images have different aspect ratios' }}
            </span>
          </div>
        </div>
      </div>
      
      <!-- Metadata Section -->
      <div class="metadata-section">
        <h4 class="section-title">
          <span class="section-icon">📅</span>
          Metadata
        </h4>
        
        <div class="metadata-grid">
          <div class="metadata-item">
            <span class="metadata-label">Created</span>
            <span class="metadata-value">{{ formatDate(retouche.created_at) }}</span>
          </div>
          
          <div class="metadata-item">
            <span class="metadata-label">Modified</span>
            <span class="metadata-value">{{ formatDate(retouche.updated_at) }}</span>
          </div>
          
          <div class="metadata-item">
            <span class="metadata-label">Before Image ID</span>
            <span class="metadata-value">{{ beforeImage?.id || 'N/A' }}</span>
          </div>
          
          <div class="metadata-item">
            <span class="metadata-label">After Image ID</span>
            <span class="metadata-value">{{ afterImage?.id || 'N/A' }}</span>
          </div>
          
          <div class="metadata-item">
            <span class="metadata-label">Retouche ID</span>
            <span class="metadata-value">{{ retouche.id }}</span>
          </div>
        </div>
      </div>
    </div>
  </template>
  
  <script setup lang="ts">
  import { ref, computed, watch } from 'vue';
  import type { Retouche, Media } from '../../../../shared/types';
  
  interface Props {
    retouche: Partial<Retouche>;
    beforeImage?: Media;
    afterImage?: Media;
  }
  
  const props = defineProps<Props>();
  const emit = defineEmits<{
    'update:retouche': [retouche: Partial<Retouche>];
    'change': [];
  }>();
  
  // État local
  const localRetouche = ref<Partial<Retouche>>({ ...props.retouche });
  const showSeo = ref(false);
  const newKeyword = ref('');
  
  // Computed
  const keywords = computed({
    get: () => {
      const seoKeywords = localRetouche.value.seo?.keywords;
      if (Array.isArray(seoKeywords)) {
        return seoKeywords;
      }
      return [];
    },
    set: (value: string[]) => {
      if (!localRetouche.value.seo) {
        localRetouche.value.seo = {};
      }
      localRetouche.value.seo.keywords = value;
      emitChange();
    }
  });
  
  const keywordsCount = computed(() => keywords.value.length);
  const descriptionLength = computed(() => (localRetouche.value.description || '').length);
  const seoTitleLength = computed(() => (localRetouche.value.seo?.title || '').length);
  const seoDescriptionLength = computed(() => (localRetouche.value.seo?.description || '').length);
  
  // Auto-génération SEO pour retouches
  const autoGeneratedSEO = computed(() => {
    const title = localRetouche.value.title || '';
    const description = localRetouche.value.description || '';
    
    return {
      title: title ? `${title} - Before & After Retouching | Valentine Arnaly` : '',
      description: description ? 
        description.length > 160 ? 
          description.substring(0, 157) + '...' : 
          description : 
        'Professional photo retouching showcase - see the dramatic before and after transformation.',
    };
  });
  
  // SEO Preview
  const displaySeoTitle = computed(() => {
    const title = localRetouche.value.seo?.title || autoGeneratedSEO.value.title;
    return title.length > 60 ? title.substring(0, 57) + '...' : title;
  });
  
  const displaySeoDescription = computed(() => {
    const description = localRetouche.value.seo?.description || autoGeneratedSEO.value.description;
    return description.length > 160 ? description.substring(0, 157) + '...' : description;
  });
  
  // Images compatibility
  const dimensionsMatch = computed(() => {
    if (!props.beforeImage || !props.afterImage) return true;
    return props.beforeImage.width === props.afterImage.width && 
           props.beforeImage.height === props.afterImage.height;
  });
  
  const aspectRatioMatch = computed(() => {
    if (!props.beforeImage || !props.afterImage) return true;
    const beforeRatio = props.beforeImage.width / props.beforeImage.height;
    const afterRatio = props.afterImage.width / props.afterImage.height;
    return Math.abs(beforeRatio - afterRatio) < 0.01;
  });
  
  // Watchers
  watch(() => props.retouche, (newRetouche) => {
    localRetouche.value = { ...newRetouche };
  }, { deep: true });
  
  // Méthodes
  const emitChange = () => {
    emit('update:retouche', localRetouche.value);
    emit('change');
  };
  
  const autoGenerateSEO = () => {
    if (!localRetouche.value.seo) {
      localRetouche.value.seo = {};
    }
    
    if (localRetouche.value.title) {
      localRetouche.value.seo.title = autoGeneratedSEO.value.title;
    }
    
    if (localRetouche.value.description) {
      localRetouche.value.seo.description = autoGeneratedSEO.value.description;
    }
    
    // Auto-generate retouching keywords
    const retouchingKeywords = extractRetouchingKeywords(
      `${localRetouche.value.title || ''} ${localRetouche.value.description || ''}`
    );
    
    if (retouchingKeywords.length > 0) {
      localRetouche.value.seo.keywords = [
        ...new Set([...keywords.value, ...retouchingKeywords])
      ].slice(0, 10);
    }
    
    emitChange();
  };
  
  const extractRetouchingKeywords = (text: string): string[] => {
    const retouchingTerms = [
      'retouche', 'retouching', 'photoshop', 'before', 'after', 'transformation',
      'editing', 'enhancement', 'correction', 'restoration', 'beauty', 'portrait',
      'photography', 'professional', 'digital', 'image', 'photo'
    ];
    
    const words = text
      .toLowerCase()
      .replace(/[^\w\s]/g, '')
      .split(/\s+/)
      .filter(word => word.length > 3);
    
    return retouchingTerms
      .filter(term => text.toLowerCase().includes(term))
      .slice(0, 5);
  };
  
  const addKeyword = () => {
    const keyword = newKeyword.value.trim().replace(/,+$/, '');
    if (keyword && !keywords.value.includes(keyword) && keywords.value.length < 10) {
      keywords.value = [...keywords.value, keyword];
      newKeyword.value = '';
    }
  };
  
  const removeKeyword = (index: number) => {
    keywords.value = keywords.value.filter((_, i) => i !== index);
  };
  
  const generateSlug = (title: string): string => {
    return title
      .toLowerCase()
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '')
      .replace(/[^a-z0-9\s-]/g, '')
      .replace(/\s+/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '');
  };
  
  const formatDate = (dateString?: string) => {
    if (!dateString) return 'N/A';
    
    const date = new Date(dateString);
    return date.toLocaleDateString('fr-FR', {
      day: 'numeric',
      month: 'short',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };
  
  const formatFileSize = (bytes: number): string => {
    if (bytes < 1024) return `${bytes}B`;
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)}KB`;
    return `${(bytes / 1024 / 1024).toFixed(1)}MB`;
  };
  
  const getFileFormat = (mimeType: string): string => {
    switch (mimeType) {
      case 'image/jpeg': return 'JPEG';
      case 'image/png': return 'PNG';
      case 'image/webp': return 'WebP';
      case 'image/gif': return 'GIF';
      default: return mimeType.replace('image/', '').toUpperCase();
    }
  };
  </script>
  
  <style scoped lang="scss">
  @import '../../styles/variables.scss';
  
  .retouche-properties {
    background: $color-white;
    border-radius: 12px;
    padding: 1.5rem;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
    
    h3 {
      color: $color-gray-dark;
      margin: 0 0 1.5rem 0;
      font-size: 1.25rem;
      font-weight: 600;
    }
  }
  
  .properties-grid {
    display: grid;
    gap: 1.5rem;
    margin-bottom: 2rem;
    
    .property-item {
      &.full-width {
        grid-column: 1 / -1;
      }
    }
  }
  
  .property-label {
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin-bottom: 0.5rem;
    font-weight: 500;
    color: $color-gray-dark;
    font-size: 0.9rem;
    
    .label-icon {
      margin-right: 0.5rem;
    }
    
    .char-count {
      font-size: 0.8rem;
      color: $color-gray-medium;
      font-weight: 400;
      transition: color 0.3s ease;
      
      &.warning {
        color: #f59e0b;
      }
      
      &.error {
        color: #ef4444;
      }
    }
  }
  
  .property-select,
  .property-input,
  .property-textarea {
    width: 100%;
    padding: 0.75rem;
    border: 1px solid $color-gray-light;
    border-radius: 6px;
    font-size: 0.9rem;
    transition: all 0.3s ease;
    
    &:focus {
      outline: none;
      border-color: $color-gray-dark;
      box-shadow: 0 0 0 3px rgba(107, 114, 128, 0.1);
    }
    
    &.warning {
      border-color: #f59e0b;
      background-color: #fffbeb;
    }
    
    &.error {
      border-color: #ef4444;
      background-color: #fef2f2;
    }
  }
  
  .property-select {
    cursor: pointer;
    background: $color-white;
  }
  
  .property-textarea {
    resize: vertical;
    min-height: 80px;
    font-family: inherit;
  }
  
  .validation-info {
    margin-top: 0.5rem;
    font-size: 0.8rem;
    
    .validation-warning {
      color: #f59e0b;
    }
    
    .validation-error {
      color: #ef4444;
    }
  }
  
  // Section styles
  .seo-section,
  .images-info-section,
  .metadata-section {
    border-top: 1px solid $color-gray-light;
    padding-top: 1.5rem;
    margin-bottom: 2rem;
  }
  
  .section-title {
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin: 0 0 1rem 0;
    font-size: 1rem;
    font-weight: 600;
    color: $color-gray-dark;
    
    .section-icon {
      margin-right: 0.5rem;
    }
    
    .toggle-section {
      background: none;
      border: none;
      cursor: pointer;
      font-size: 1.2rem;
      color: $color-gray-medium;
      padding: 0.25rem;
      
      &:hover {
        color: $color-gray-dark;
      }
    }
  }
  
  // SEO specific styles
  .seo-fields {
    display: grid;
    gap: 1rem;
  }
  
  .seo-auto-generate {
    display: flex;
    align-items: center;
    gap: 1rem;
    padding: 1rem;
    background: lighten($color-gray-light, 5%);
    border-radius: 8px;
    
    .auto-generate-btn {
      background: $color-gray-dark;
      color: $color-white;
      border: none;
      border-radius: 6px;
      padding: 0.5rem 1rem;
      font-size: 0.9rem;
      cursor: pointer;
      transition: all 0.3s ease;
      
      &:hover:not(:disabled) {
        background: lighten($color-gray-dark, 10%);
      }
      
      &:disabled {
        opacity: 0.5;
        cursor: not-allowed;
      }
    }
    
    small {
      color: $color-gray-medium;
      font-size: 0.8rem;
    }
  }
  
  .seo-preview {
    margin-top: 1rem;
    padding: 1rem;
    background: lighten($color-gray-light, 7%);
    border-radius: 8px;
    
    h5 {
      margin: 0 0 1rem 0;
      color: $color-gray-dark;
      font-size: 0.9rem;
      font-weight: 600;
    }
    
    .google-preview {
      background: $color-white;
      border-radius: 8px;
      padding: 1rem;
      box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
      
      .preview-url {
        font-size: 0.8rem;
        color: #1a73e8;
        margin-bottom: 0.25rem;
        
        .domain {
          font-weight: 500;
        }
        
        .path {
          color: #5f6368;
        }
      }
      
      .preview-title {
        font-size: 1.1rem;
        color: #1a0dab;
        font-weight: 500;
        margin-bottom: 0.25rem;
        cursor: pointer;
        
        &:hover {
          text-decoration: underline;
        }
      }
      
      .preview-description {
        font-size: 0.9rem;
        color: #4d5156;
        line-height: 1.4;
      }
    }
  }
  
  // Keywords styles
  .keywords-input {
    border: 1px solid $color-gray-light;
    border-radius: 6px;
    padding: 0.5rem;
    transition: border-color 0.3s ease;
    
    &:focus-within {
      border-color: $color-gray-dark;
    }
    
    .keywords-list {
      display: flex;
      flex-wrap: wrap;
      gap: 0.5rem;
      margin-bottom: 0.5rem;
      
      .keyword-tag {
        background: lighten($color-gray-light, 3%);
        color: $color-gray-dark;
        padding: 0.25rem 0.5rem;
        border-radius: 4px;
        font-size: 0.8rem;
        display: flex;
        align-items: center;
        gap: 0.25rem;
        
        .remove-keyword {
          background: none;
          border: none;
          cursor: pointer;
          color: $color-gray-medium;
          font-size: 0.9rem;
          padding: 0;
          line-height: 1;
          
          &:hover {
            color: #dc2626;
          }
        }
      }
    }
    
    .keyword-input {
      border: none;
      outline: none;
      padding: 0.25rem;
      font-size: 0.9rem;
      width: 100%;
      background: transparent;
    }
  }
  
  .keywords-help {
    margin-top: 0.5rem;
    
    small {
      color: $color-gray-medium;
      font-size: 0.8rem;
    }
  }
  
  // Images info styles
  .images-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 1rem;
    margin-bottom: 1.5rem;
    
    .image-info-card {
      background: lighten($color-gray-light, 5%);
      padding: 1rem;
      border-radius: 8px;
      
      h5 {
        margin: 0 0 0.75rem 0;
        font-size: 0.9rem;
        font-weight: 600;
        color: $color-gray-dark;
      }
      
      .image-details {
        .detail-item {
          display: flex;
          justify-content: space-between;
          margin-bottom: 0.5rem;
          
          .detail-label {
            font-size: 0.8rem;
            color: $color-gray-medium;
            font-weight: 500;
          }
          
          .detail-value {
            font-size: 0.8rem;
            color: $color-gray-dark;
            font-weight: 500;
          }
        }
      }
    }
  }
  
  .compatibility-check {
    .check-item {
      display: flex;
      align-items: center;
      gap: 0.5rem;
      margin-bottom: 0.5rem;
      font-size: 0.85rem;
      
      &.success .check-text {
        color: #065f46;
      }
      
      &.warning .check-text {
        color: #92400e;
      }
    }
  }
  
  // Metadata styles
  .metadata-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 1rem;
  }
</style>